### ISSUE TITLE
Security Data Issues Secrets in clear text

### ISSUE THREAD

**Issue by shaybenb** [ciprian-radu/rent-a-car#1]
Hi,<br><br>url : https://github.com/ciprian-radu/rent-a-car/blob/4bbe5f34e450f813e880bf8507c837d22648689c/application/external-interfaces/auth-client/src/main/resources/application-heroku.yml <br><br>You have commit that need to remove from the github history<br>attacker can see it and use it ...<br><br>encrypt your secrets !!!!<br><br>Our Bug Help you to be more Secure and protect your data ?<br>Buy me a coffee (or more likely a beer)<br>https://www.paypal.com/paypalme/bugbounty1/150USD<br>https://www.buymeacoffee.com/bugbounty<br>☕☕☕☕☕

**Comment by ciprian-radu** [comment]
Those credentials are no longer valid. What's history remains history.
That database connection was for demo purposes anyway. So, nothing critical but, thanks for letting me know.
